preload = ~/.config/wallpapers/Pokemon/1351987.jpeg
preload = ~/.config/wallpapers/Anime/1317094.png
preload = ~/.config/wallpapers/Anime/168847-man_de_nu_hai-ka_tong-ren_men_zai_zi_ran_jie-kuai_le_de-yang_guang-3840x2160.jpg


wallpaper = DP-1,~/.config/wallpapers/Anime/168847-man_de_nu_hai-ka_tong-ren_men_zai_zi_ran_jie-kuai_le_de-yang_guang-3840x2160.jpg
wallpaper = HDMI-A-1,~/.config/wallpapers/Anime/168847-man_de_nu_hai-ka_tong-ren_men_zai_zi_ran_jie-kuai_le_de-yang_guang-3840x2160.jpg
