# Please note not all available settings / options are set here.
# For a full list, see the wiki

# You can split this configuration into multiple files
# Create your files separately and then link them to this file like this:
# source = ~/.config/hypr/myColors.conf

source = ~/.local/share/hypr/land/envs.conf
source = ~/.local/share/hypr/land/autostart.conf
source = ~/.local/share/hypr/land/monitors.conf
source = ~/.local/share/hypr/land/permissions.conf
source = ~/.local/share/hypr/land/looknfeel.conf
source = ~/.local/share/hypr/land/input.conf
source = ~/.local/share/hypr/land/window.conf
source = ~/.local/share/hypr/land/transparent.conf
source = ~/.local/share/hypr/land/plugins.conf
source = ~/.local/share/hypr/land/cursor.conf
source = ~/.local/share/hypr/land/keybindings.conf

source = ~/.local/private/hypr/hyprland.conf
