##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

workspace = 1, monitor:HDMI-A-2
workspace = 2, monitor:HDMI-A-2
workspace = 3, monitor:HDMI-A-2
workspace = 4, monitor:HDMI-A-2
workspace = 5, monitor:HDMI-A-2
workspace = 6, monitor:DP-2
workspace = 7, monitor:DP-2
workspace = 8, monitor:DP-2
workspace = 9, monitor:DP-2
workspace = 10, monitor:DP-2

# workspace = 1, on-created-empty:[fullscreen] $terminal
# workspace = 2, on-created-empty:[tiled] $browser

workspace = special:terminal, on-created-empty:[float]$terminal
workspace = special:spotify, on-created-empty:[tiled]spotify
workspace = special:workmsg, on-created-empty:[tiled]$workmsg
workspace = special:baby, on-created-empty:[tiled]$babycam

# special workspace (scratchpad)
bind = $mainMod, S, togglespecialworkspace, scratchpad
bind = $mainMod SHIFT, S, movetoworkspace, special:scratchpad

bind = $mainMod, P, togglespecialworkspace, spotify
bind = $mainMod SHIFT, P, movetoworkspace, special:spotify

# baby cam
bind = $mainMod, B, togglespecialworkspace, baby
bind = $mainMod SHIFT, B, movetoworkspace, special:baby

bind = $mainMod, D, togglespecialworkspace, workmsg
bind = $mainMod SHIFT, D, movetoworkspace, special:workmsg

bind = $mainMod, A, togglespecialworkspace, terminal
bind = $mainMod SHIFT, A, movetoworkspace, special:terminal

bind = $mainMod, X, togglespecialworkspace, unknown
bind = $mainMod SHIFT, X, movetoworkspace, special:unknown
