# Please note not all available settings / options are set here.
# For a full list, see the wiki

# You can split this configuration into multiple files
# Create your files separately and then link them to this file like this:
# source = ~/.config/hypr/myColors.conf

source = ~/.local/share/workspace/hyprland/envs.conf
source = ~/.local/share/workspace/hyprland/autostart.conf
source = ~/.local/share/workspace/hyprland/theme.conf
source = ~/.local/share/workspace/hyprland/monitors.conf
source = ~/.local/share/workspace/hyprland/permissions.conf
source = ~/.local/share/workspace/hyprland/looknfeel.conf
source = ~/.local/share/workspace/hyprland/input.conf

source = ~/.local/share/workspace/hyprland/bindings/modkey.conf
source = ~/.local/share/workspace/hyprland/bindings/utilities.conf
source = ~/.local/share/workspace/hyprland/bindings/workspace.conf
source = ~/.local/share/workspace/hyprland/bindings/clipboard.conf
source = ~/.local/share/workspace/hyprland/bindings/screenshot.conf
source = ~/.local/share/workspace/hyprland/bindings/zoom.conf
