# Please note not all available settings / options are set here.
# For a full list, see the wiki

# You can split this configuration into multiple files
# Create your files separately and then link them to this file like this:
# source = ~/.config/hypr/myColors.conf

source = ~/.local/share/workspace/hypr/land/envs.conf
source = ~/.local/share/workspace/hypr/land/autostart.conf
source = ~/.local/share/workspace/hypr/land/theme.conf
source = ~/.local/share/workspace/hypr/land/monitors.conf
source = ~/.local/share/workspace/hypr/land/permissions.conf
source = ~/.local/share/workspace/hypr/land/looknfeel.conf
source = ~/.local/share/workspace/hypr/land/input.conf

source = ~/.local/share/workspace/hypr/land/bindings/modkey.conf
source = ~/.local/share/workspace/hypr/land/bindings/utilities.conf
source = ~/.local/share/workspace/hypr/land/bindings/workspace.conf
source = ~/.local/share/workspace/hypr/land/bindings/clipboard.conf
source = ~/.local/share/workspace/hypr/land/bindings/screenshot.conf
source = ~/.local/share/workspace/hypr/land/bindings/zoom.conf
