[env]
TERM = "xterm-256color"

[font]
size = 12

[font.normal]
family = "monospace"
style = "Regular"
[font.bold]
family = "monospace"
style = "bold"
[font.italic]
family = "monospace"
style = "italic"
[font.bold_italic]
family = "monospace"
style = "Bold Italic"

# we set font order by .config/fontconfig/fonts.conf
# Comic Code
# JetBrainsMono Nerd Font Mono
# LXGW WenKai Mono 霞鶩文楷
# Noto Sans Mono CJK TC
# Noto Mono Mono CJK JP
# Noto Mono Mono CJK KR
# Noto Color Emoji😀

[mouse]
hide_when_typing = true

[scrolling]
history = 50000
multiplier = 20

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 1.0
startup_mode = "Maximized"

[window.padding]
x = 5
y = 0

[general]
live_config_reload = true
import = ["colors.toml"]

[cursor]
style = { shape = "Block", blinking = "On" }

[keyboard]
bindings = [
	{ key = "C", mods = "Control|Shift", action = "Copy" },
	{ key = "V", mods = "Control|Shift", action = "Paste" },
	{ key = "F", mods = "Control", action = "SearchForward" },
]

[selection]
save_to_clipboard = true
