# Screenshot
env = HYPRSHOT_DIR, ~/Pictures/Screenshots
bind = $mainMod CTRL, 1, exec, hyprshot -m output --clipboard-only
bind = $mainMod CTRL, 2, exec, hyprshot -m window --clipboard-only
bind = $mainMod CTRL, 3, exec, hyprshot -m region --clipboard-only
bind = $mainMod CTRL, 4, exec, hyprshot -m output
bind = $mainMod CTRL, 5, exec, hyprshot -m window
bind = $mainMod CTRL, 6, exec, hyprshot -m region
