#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# Sync DBus env
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_RUNTIME_DIR HYPRLAND_INSTANCE_SIGNATURE

# Daemons
exec-once = sleep 1
exec-once = hypridle
exec-once = awww-daemon # we symbol linked this to swww `sudo ln -s /usr/bin/awww /usr/bin/swww` see: https://github.com/anufrievroman/waypaper/issues/254
exec-once = /usr/lib/polkit-kde-authentication-agent-1

# Apps
exec-once = swww img ~/.local/share/wallpapers/3825.jpg
exec-once = byte4work-launch-waybar
exec-once = uwsm-app -- swaync
exec-once = uwsm-app -- fcitx5 -d
exec-once = uwsm-app -- elephant
exec-once = uwsm-app -- walker --gapplication-service
exec-once = uwsm-app -- swayosd-server
exec-once = uwsm-app -- glint

exec-once = wl-paste --type text --watch cliphist store

exec-once = [workspace 1 silent] $terminal
exec-once = [workspace 2 silent] $browser

exec-once = /usr/bin/kwalletd6
# exec-once = xhost +SI:localuser:root

exec-once = hyprpm reload
exec-once = byte4work-watch-dots
