#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# Sync DBus env
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE GPG_TTY
exec-once = gpg-connect-agent updatestartuptty /bye
exec-once = gpg-connect-agent /bye
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_RUNTIME_DIR HYPRLAND_INSTANCE_SIGNATURE

# Daemons
exec-once = sleep 1
exec-once = hypridle
exec-once = awww-daemon # we symbol linked this to swww `sudo ln -s /usr/bin/awww /usr/bin/swww` see: https://github.com/anufrievroman/waypaper/issues/254
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = gnome-keyring-daemon --start --components=secrets,pkcs11,ssh

# Apps
exec-once = sleep 1.5 && byte4work-launch-waybar
exec-once = uwsm-app -- swaync
exec-once = uwsm-app -- fcitx5 -d
exec-once = uwsm-app -- elephant
exec-once = uwsm-app -- walker --gapplication-service
exec-once = uwsm-app -- swayosd-server
exec-once = uwsm-app -- glint

exec-once = wl-paste --watch cliphist store

# exec-once = /usr/bin/kwalletd6
# exec-once = xhost +SI:localuser:root

# dark theme
exec-once = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
exec-once = gsettings set org.gnome.desktop.interface gtk-theme 'adw-gtk3-dark'
exec-once = gsettings set org.gnome.desktop.interface font-name 'sans-serif 11'
exec-once = gsettings set org.gnome.desktop.interface document-font-name 'sans-serif 11'
exec-once = gsettings set org.gnome.desktop.interface monospace-font-name 'monospace 11'

exec = hyprshade auto

# exec-once = hyprpm reload
exec-once = byte4work-watch-dots

exec-once = sleep 3
exec-once = [workspace special:scratchpadterm] $terminal -e bash -c "tmux new-session -A -s scratchpad; exec bash"
exec-once = [workspace special:work-msg silent] $work_msg
exec-once = [workspace special:personal-msg silent] $personal_msg
exec-once = [workspace special:music silent] $music
exec-once = [workspace 1 silent] $terminal
exec-once = [workspace 2 silent] $browser
