# $terminal = alacritty
$terminal = ghostty
# $file_manager = thunar
$file_manager = nautilus
$terminal_file_manager = $terminal -e yazi ~/Downloads
$menu = wofi
$emoji_picker = rofimoji --selector $menu --action clipboard
# $menu = byte4work-walker-entry
# $browser = firefox
$browser = librewolf
# $browser = zen-browser
# $browser = google-chrome-stable
# $browser = brave
# $browser = chromium
$work_msg = vesktop
$personal_msg = signal-desktop
$babycam = byte4work-babycam
# $music = spotify
$music = $terminal --title="spotify-player" -e spotify_player

#############################
### ENVIRONMENT VARIABLES ###
#############################

env = PRIMARY_MONITOR,DP-1

# See https://wiki.hyprland.org/Configuring/Environment-variables/

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

env = HYPRSHOT_DIR,$HOME/Pictures/Screenshots
env = SCREENSHOT_DIR,$HOME/Pictures/Screenshots

#for kde apps you need to install: sudo pacman -S qt5ct qt6ct kvantum kvantum breeze-icons
#you will need to set dark theme for qt apps from kde more difficult thans with gnome :D:
env = QT_QPA_PLATFORMTHEME,qt6ct   # for Qt apps# Theme

env = QT_QPA_PLATFORM,wayland
env = GDK_BACKEND,wayland
env = MOZ_ENABLE_WAYLAND,1
env = ELECTRON_OZONE_PLATFORM_HINT,wayland

# scripts locations
env = PATH,/home/neil/.local/bin/wayland:/home/neil/.local/bin/common:/home/neil/.local/bin/hyprland:/home/neil/.local/private/bin:/usr/local/bin:/usr/bin

# Set environment variables for applications launched within Hyprland
# This ensures Qt applications (like OBS) use the Wayland backend.
env = QT_QPA_PLATFORM,wayland

env = TERMINAL,$terminal

env = mesa_glthread,true
