plugin {
    dynamic-cursors {
        enabled = true
        mode = tilt

        threshold = 2

        tilt {
            limit = 5000
            function = negative_quadratic
            full_tilt = 60
        }

        # macOS 晃動變大功能
        shake {
            enabled = true
            nearest = true
            threshold = 5.0
            base = 4.0
            speed = 4.0
            timeout = 500
        }

        # 高解析度支援
        hyprcursor {
            enabled = true
            nearest = true
        }
    }
}
