# Basic
windowrule {
    name = global-transparent
    match:class = .*
    opacity = 0.96 override 0.96 override
}

# Set to no transparent
windowrule {
    name = browser-transparent
    match:class = ^(firefox|brave-browser|google-chrome|chromium|zen)$
    opacity = 1.0 override 1.0 override
}

windowrule {
    name = media-transparent
    match:class = ^(mpv|vlc)$
    opacity = 1.0 override 1.0 override
}

# --- 終端機設定 (從一般到特殊) ---

# Terminal
windowrule {
    name = terminal-transparent
    match:class = ^(com.mitchellh.ghostty|Alacritty|kitty)$
    opacity = 0.85 override 0.85 override
}
