# 設定全域 fullscreen 視窗透明度
windowrule {
    name = global-fullscreen-transparent
    match:class = .*
    opacity = 1.0 override 1.0 override
}

# 這裡將所有視窗設定為 90% 不透明 (10% 透明)
windowrule {
    name = global-transparent
    match:class = .*
    opacity = 0.90 override 0.90 override
}

# Terminal
windowrule {
    name = terminal-transparent
    match:class = ^(com.mitchellh.ghostty|Alacritty|kitty)$
    opacity = 0.85 override 0.85 override
}

# vscode tools
windowrule {
    name = vscode-transparent
    match:class = ^(code-oss)$
    opacity = 0.98 override 0.98 override
}

# Browsers
windowrule {
    name = browser-transparent
    match:class = ^(firefox|brave-browser|google-chrome|chromium)$
    opacity = 1.0 override 1.0 override
}

# Media Players
windowrule {
   name = media-transparent
    match:class = ^(mpv|vlc)$
    opacity = 1.0 override 1.0 override
}

# Others
windowrule {
    name = apps-transparent
    match:class = ^(waypaper|vesktop|gimp|qimgv|zoom|anydesk|amdgpu_top)$
    opacity = 1.0 override 1.0 override
}

