# Basic
windowrule {
    name = global-transparent
    match:class = .*
    opacity = 0.96 override 0.96 override
}

# Set to no transparent
windowrule {
    name = browser-transparent
    match:class = ^(firefox|brave-browser|google-chrome|chromium|zen|librewolf)$
    opacity = 1.0 override 1.0 override
}


# Set to no transparent
windowrule {
    name = msg-transparent
    match:class = ^(vesktop|Signal)$
    opacity = 1.0 override 1.0 override
}

windowrule {
    name = media-transparent
    match:class = ^(mpv|vlc|ffplay)$
    opacity = 1.0 override 1.0 override
}

# Terminal
windowrule {
    name = terminal-transparent
    match:class = ^(com.mitchellh.ghostty|Alacritty|kitty|foot)$
    opacity = 0.80 override 0.80 override
	no_blur = false
}
windowrule = match:class ^(com.mitchellh.ghostty|Alacritty|kitty|foot)$, match:fullscreen 1, opacity 0.9 override 0.9 override 0.9 override, no_blur false
