windowrulev2 = float, class:org.pulseaudio.pavucontrol
windowrulev2 = size 80% 50%, class:org.pulseaudio.pavucontrol
windowrulev2 = center, class:org.pulseaudio.pavucontrol

windowrulev2 = float, class:waypaper
windowrulev2 = size 60% 80%, class:waypaper
windowrulev2 = center, class:waypaper

windowrulev2 = float, class:vlc
