###############
### WINDOWS ###
###############
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

windowrule {
    name = pavucontrol-window
    match:class = ^(org.pulseaudio.pavucontrol)$
    float = true
    center = true
    size = 80% 50%
}

windowrule {
    name = waypaper-window
    match:class = ^(waypaper)$
    float = true
    center = true
    size = 60% 80%
}

# Show Me The Key
windowrule {
    name = key-display-overlay
    match:class = ^(showmethekey-gtk)$

    # Static Effects
    float = on
    pin = on
    no_initial_focus = on

    # Dynamic Effects
    no_focus = on
    no_shadow = on

    # place and size
    move = (monitor_w*8/10) (monitor_h*8/10)
    size = 600 150
}

windowrule {
    name = satty-screenshot
    match:class = ^(com.gabm.satty)$
    float = on
    center = on
    # size = 80% 80%
    pin = true
}

windowrule {
    name = media-players-window
    match:class = ^(mpv|vlc|ffplay)$
    float = on
    pin = false
    size = 800 450
    center = on

    # on 4k resolution, 16:9 aspect ratio

    # right bottom 720p
    # size = 800 450
    # move = 3000 1670 # (3840-800-40, 2160-450-40)

    # right bottom 1/4
    # size = 960 540
    # move = 2840 1580 # (3840-960-40, 2160-540-40)

    #on 2k resolution, 16:9 aspect ratio

    # 物理 720p 比例 (邏輯約 853x480)
    # size = 853 480
    # move = 1680 940  # (2560-853-27, 1440-480-20)

    # 物理 1/4 螢幕 (物理 960x540 -> 邏輯 640x360)
    # size = 640 360
    # move = 1880 1040 # (2560-640-40, 1440-360-40)
}


windowrule {
    name = babycam-window
    match:initial_title = BabyCam # for mpv and ffplay
    match:title = ^(BabyCam).* # for vlc
    monitor=$PRIMARY_MONITOR
    size = 320 180
    move = (monitor_w*8.7/10) (monitor_h*8.65/10)
    float = on
    pin = on
}

windowrule {
    name = workspace-2-always-group
    match:workspace = 2
    group = on
}

windowrule {
    name = scratchpadterm-auto-style
    match:workspace = special:scratchpad-term
    match:class = ^(com.mitchellh.ghostty|Alacritty|kitty|foot)$
    monitor=$PRIMARY_MONITOR
    size = (monitor_w*7/10) (monitor_h*7/10)
    float = on
    center = on
    # opacity = 1.0 override 1.0 override
}

windowrule {
    name = work-msg-auto-style
    match:workspace = special:work-msg
    opacity = 1.0 override 1.0 override
}

windowrule {
    name = personal-msg-auto-style
    match:workspace = special:personal-msg
    opacity = 1.0 override 1.0 override
}


windowrule {
    name = music-auto-style
    match:workspace = special:music
    size = (monitor_w*8/10) (monitor_h*8/10)
    float = on
    center = on
    opacity = 1.0 override 1.0 override
}

windowrule {
    name = init-music
    match:class = ^(spotify)$
    workspace = special:music silent
}

windowrule {
    name = waydrop-window
    match:initial_class = ^(Waydroid)$
    float = on
    center = on
    opacity = 1.0 override 1.0 override
}

windowrule {
    name = place-work-msg
    match:initial_class = ^(vesktop)$
    workspace = special:work-msg silent
}


windowrule {
    name = place-personal-msg
    match:initial_class = ^(signal)$
    workspace = special:personal-msg silent
}
