###############
### WINDOWS ###
###############
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

windowrule {
    name = pavucontrol-window
    match:class = ^(org.pulseaudio.pavucontrol)$
    float = true
    center = true
    size = 80% 50%
}

windowrule {
    name = waypaper-window
    match:class = ^(waypaper)$
    float = true
    center = true
    size = 60% 80%
}

# windowrule {
#     name = media-players-window
#     match:class = ^(vlc)$
#     float = true
#     center = true
#     size = 60% 80%
# }

# Show Me The Key
windowrule {
    name = key-display-overlay
    match:class = ^(showmethekey-gtk)$

    # Static Effects
    float = on
    pin = on
    no_initial_focus = on

    # Dynamic Effects
    no_focus = on
    no_shadow = on

    # place and size
    move = (monitor_w*8/10) (monitor_h*8/10)
    size = 600 150
}

windowrule {
    name = satty-screenshot
    match:class = ^(com.gabm.satty)$
    float = on
    center = on
    # size = 80% 80%
    pin = true
}

windowrule {
    name = mpv-floating
    match:class = ^(mpv)$
    float = on
    size = 800 450
    pin = false
    move  =100%-820 100%-500
}
