[env]
TERM = "xterm-256color"

[font]
size = 28

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[mouse]
hide_when_typing = true

[scrolling]
history = 50000
multiplier = 20

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.9
startup_mode = "Maximized"

[window.padding]
x = 5
y = 0

[general]
live_config_reload = true

[keyboard]
bindings = [
  # `Ctrl+F` to open tmux sessionizer, not working
  { key = "F", mods = "Control|Shift", command = { program = "alacritty", args = [ "-e", "zsh", "-ic", "~/scripts/tmux-sessionizer.sh" ] } },
]
