background = {{colors.background.default.hex}}
foreground = {{colors.on_background.default.hex}}

palette = 0={{colors.surface_variant.default.hex}}
palette = 1={{colors.error.default.hex}}
palette = 2={{colors.primary.default.hex}}
palette = 3={{colors.secondary.default.hex}}
palette = 4={{colors.tertiary.default.hex}}
palette = 5={{colors.primary_container.default.hex}}
palette = 6={{colors.secondary_container.default.hex}}
palette = 7={{colors.on_surface.default.hex}}
