# fs=yes # 自動全螢幕

# 畫質與硬體加速
# profile=high-quality
# 降低縮放算法的消耗（從 ewa_lanczos 降到 bilinear 或 fast）
profile=fast
# hwdec=auto-safe      # 自動開啟硬體解碼，減輕 CPU 負擔
hwdec=vaapi
vo=gpu               # 使用 GPU 渲染
gpu-context=wayland  # 針對你的 Hyprland 環境
# gpu-api=vulkan
# vd-lavc-dr=yes

# 字幕自動開啟
sid=1
slang=zh-Hant,zh-TW,zh,en

# cache and preloaded
cache=yes
cache-pause-initial=yes
cache-pause-wait=5
demuxer-max-bytes=1024M
demuxer-max-back-bytes=1024M

keep-open=yes
save-position-on-quit=yes
force-window=yes
