r add video-rotate 90
R add video-rotate -90

l seek  5                          # 往後 5 秒
h seek -5                          # 往前 5 秒
j seek -60                         # 往前 1 分鐘
k seek  60                         # 往後 1 分鐘
f cycle fullscreen                 # 切換全螢幕
q quit                             # 退出

# 當檔案被拖進視窗時，加入清單並立刻跳到該檔案播放
# DRAG_AND_DROP loadfile "${drag-and-drop-target}" append-play
