$terminal = alacritty
$fileManager = nautilus
# $menu = wofi --show drun
$menu = ~/.local/bin/launch-walker
$browser = firefox
# $browser = google-chrome-stable
# $browser = brave
# $browser = chromium --enable-features=UseOzonePlatform --ozone-platform=wayland --use-gl=angle --enable-features=Vulkan --enable-webgl --ignore-gpu-blacklist --enable-features=WebRTCPipwireCapturer
$workmsg = vesktop
$babycam = ~/.local/private/scripts/baby_cam

#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hyprland.org/Configuring/Environment-variables/

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

#for kde apps you need to install: sudo pacman -S qt5ct qt6ct kvantum kvantum breeze-icons
#you will need to set dark theme for qt apps from kde more difficult thans with gnome :D:
env = QT_QPA_PLATFORMTHEME,qt6ct   # for Qt apps# Theme

env = QT_QPA_PLATFORM,wayland
env = GDK_BACKEND,wayland
env = MOZ_ENABLE_WAYLAND,1
env = ELECTRON_OZONE_PLATFORM_HINT,wayland
