# clipboard management, requires cliphist and wl-copy, its a simple script that lists the clipboard history and allows you to select an entry to copy it back to the clipboard
bind = $mainMod $altMod, C, exec, $launcher -m clipboard
# bind = $mainMod $altMod, C, exec, byte4work-wofi-clipboard
# bind = $mainMod $altMod, C, exec, cliphist list | wofi --dmenu | cliphist decode | wl-copy
