# --- Screenshot ---

env = HYPRSHOT_DIR, $HOME/Pictures/Screenshots
env = SCREENSHOT_DIR, $HOME/Pictures/Screenshots

# 截圖整個螢幕 (Ctrl+1)
bind = $mainMod CTRL, 1, exec, grim - | tee $SCREENSHOT_DIR/$(date +'%Y%m%d-%H%M%S').png | wl-copy && notify-send "Screenshot saved & copied"
# 截圖視窗 (Ctrl+2)
bind = $mainMod CTRL, 2, exec, grim -g "$(slurp)" - | tee $SCREENSHOT_DIR/$(date +'%Y%m%d-%H%M%S').png | wl-copy && notify-send "Screenshot saved & copied"
# 截圖區域 (Ctrl+3)
bind = $mainMod CTRL, 3, exec, grim -g "$(slurp)" - | tee $SCREENSHOT_DIR/$(date +'%Y%m%d-%H%M%S').png | wl-copy && notify-send "Screenshot saved & copied"

# --- Screenshot (Edit with Satty) ---
# 截圖整個螢幕並用 satty 編輯 (Ctrl+Shift+1)
bind = $mainMod CTRL SHIFT, 1, exec, grim - | satty --filename - --fullscreen --output-filename $SCREENSHOT_DIR/$(date +'%Y%m%d-%H%M%S').png
# 截圖視窗並用 satty 編輯 (Ctrl+Shift+2)
bind = $mainMod CTRL SHIFT, 2, exec, grim -g "$(slurp)" - | satty --filename - --output-filename $SCREENSHOT_DIR/$(date +'%Y%m%d-%H%M%S').png
# 截圖選取區域並用 satty 編輯 (Ctrl+Shift+3)
bind = $mainMod CTRL SHIFT, 3, exec, grim -g "$(slurp)" - | satty --filename - --output-filename $SCREENSHOT_DIR/$(date +'%Y%m%d-%H%M%S').png
