# Screenshot
env = HYPRSHOT_DIR, $HOME/Pictures/Screenshots
bind = $mainMod CTRL, 1, exec, hyprshot -m output --clipboard-only
bind = $mainMod CTRL, 2, exec, hyprshot -m window --clipboard-only
bind = $mainMod CTRL, 3, exec, hyprshot -m region --clipboard-only
bind = $mainMod CTRL SHIFT, 1, exec, hyprshot -m output
bind = $mainMod CTRL SHIFT, 2, exec, hyprshot -m window
bind = $mainMod CTRL SHIFT, 3, exec, hyprshot -m region
