##################
### WORKSPACES ###
##################
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

workspace = 1, monitor:DP-1
workspace = 2, monitor:DP-1
workspace = 3, monitor:DP-1
workspace = 4, monitor:DP-1
workspace = 5, monitor:DP-1
workspace = 6, monitor:HDMI-A-1
workspace = 7, monitor:HDMI-A-1
workspace = 8, monitor:HDMI-A-1
workspace = 9, monitor:HDMI-A-1
workspace = 10, monitor:HDMI-A-1

# workspace = 1, on-created-empty:[fullscreen] $terminal
# workspace = 2, on-created-empty:[tiled] $browser

workspace = special:terminal, on-created-empty:[float]$terminal
workspace = special:spotify, on-created-empty:[tiled]spotify
workspace = special:workmsg, on-created-empty:[tiled]$workmsg
workspace = special:baby, on-created-empty:[tiled]$babycam

# special workspace (scratchpad)
bind = $mainMod, S, togglespecialworkspace, scratchpad
bind = $mainMod SHIFT, S, movetoworkspace, special:scratchpad

bind = $mainMod, P, togglespecialworkspace, spotify
bind = $mainMod SHIFT, P, movetoworkspace, special:spotify

# baby cam
bind = $mainMod, B, togglespecialworkspace, baby
bind = $mainMod SHIFT, B, movetoworkspace, special:baby

bind = $mainMod, D, togglespecialworkspace, workmsg
bind = $mainMod SHIFT, D, movetoworkspace, special:workmsg

bind = $mainMod, A, togglespecialworkspace, terminal
bind = $mainMod SHIFT, A, movetoworkspace, special:terminal

bind = $mainMod, X, togglespecialworkspace, unknown
bind = $mainMod SHIFT, X, movetoworkspace, special:unknown
