##################
### WORKSPACES ###
##################
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

workspace = 1, monitor:DP-1
workspace = 2, monitor:DP-1
workspace = 3, monitor:DP-1
workspace = 4, monitor:DP-1
workspace = 5, monitor:DP-1
workspace = 6, monitor:HDMI-A-1
workspace = 7, monitor:HDMI-A-1
workspace = 8, monitor:HDMI-A-1
workspace = 9, monitor:HDMI-A-1
workspace = 10, monitor:HDMI-A-1

workspace = special:terminal, on-created-empty:[float]$terminal
workspace = special:music, on-created-empty:[tiled]$music
workspace = special:workmsg, on-created-empty:[tiled]$workmsg

#########################
### Special Workspace ###
#########################
bind = $mainMod, D, togglespecialworkspace, workmsg
bind = $mainMod SHIFT, D, movetoworkspace, special:workmsg

bind = $mainMod, V, togglespecialworkspace, music
bind = $mainMod SHIFT, V, movetoworkspace, special:music

# scratchpad
bind = $mainMod, S, togglespecialworkspace, scratchpad01
bind = $mainMod SHIFT, S, movetoworkspace, special:scratchpad01

bind = $mainMod, X, togglespecialworkspace, scratchpad02
bind = $mainMod SHIFT, X, movetoworkspace, special:scratchpad02

bind = $mainMod, A, togglespecialworkspace, scratchpad03
bind = $mainMod SHIFT, A, movetoworkspace, special:scratchpad03

###########################
### SubMap - scratchpad ###
###########################

bind = $mainMod, P, submap, scratchpad

submap = scratchpad

binde = $mainMod SHIFT, Q, movetoworkspacesilent, special:unknown01
binde = $mainMod SHIFT, W, movetoworkspacesilent, special:unknown02
binde = $mainMod SHIFT, E, movetoworkspacesilent, special:unknown03

# 切換 (Toggle) 各種 Workspace
binde = , Q, togglespecialworkspace, unknown01
binde = , W, togglespecialworkspace, unknown02
binde = , E, togglespecialworkspace, unknown03

binde = , A, togglespecialworkspace, terminal

bind = , escape, submap, reset
bind = , catchall, submap, reset # any key to exit

submap = reset
