##################
### WORKSPACES ###
##################
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

workspace = 1, monitor:DP-1
workspace = 2, monitor:DP-1
workspace = 3, monitor:DP-1
workspace = 4, monitor:DP-1
workspace = 5, monitor:DP-1
workspace = 6, monitor:HDMI-A-1
workspace = 7, monitor:HDMI-A-1
workspace = 8, monitor:HDMI-A-1
workspace = 9, monitor:HDMI-A-1
workspace = 10, monitor:HDMI-A-1

workspace = special:scratchpad-term, on-created-empty:[float]$terminal -e bash -c "tmux new-session -A -s scratchpad; exec bash"
workspace = special:music, on-created-empty:[tiled]$music
workspace = special:work-msg, on-created-empty:[tiled]$work_msg
workspace = special:personalmsg, on-created-empty:[tiled]$personal_msg

#########################
### Special Workspace ###
#########################
bind = $mainMod, D, togglespecialworkspace, work-msg
bind = $mainMod SHIFT, D, movetoworkspace, special:work-msg

bind = $mainMod, V, togglespecialworkspace, music
bind = $mainMod SHIFT, V, movetoworkspace, special:music

bind = $mainMod, X, togglespecialworkspace, personal-msg
bind = $mainMod SHIFT, X, movetoworkspace, special:personal-msg

bind = $mainMod, A, togglespecialworkspace, scratchpad-term
bind = $mainMod SHIFT, A, movetoworkspace, special:scratchpad-term

# scratchpad
bind = $mainMod, S, togglespecialworkspace, scratchpad_S
bind = $mainMod SHIFT, S, movetoworkspace, special:scratchpad_S

